# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yanyg/workspace/softmax/code

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yanyg/workspace/softmax/code

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yanyg/workspace/softmax/code/CMakeFiles /Users/yanyg/workspace/softmax/code/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yanyg/workspace/softmax/code/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named train

# Build rule for target.
train: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 train
.PHONY : train

# fast build rule for target.
train/fast:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/build
.PHONY : train/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named predict

# Build rule for target.
predict: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 predict
.PHONY : predict

# fast build rule for target.
predict/fast:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/build
.PHONY : predict/fast

Function_SOFTMAX.o: Function_SOFTMAX.cpp.o

.PHONY : Function_SOFTMAX.o

# target to build an object file
Function_SOFTMAX.cpp.o:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/Function_SOFTMAX.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Function_SOFTMAX.cpp.o
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/Function_SOFTMAX.cpp.o
.PHONY : Function_SOFTMAX.cpp.o

Function_SOFTMAX.i: Function_SOFTMAX.cpp.i

.PHONY : Function_SOFTMAX.i

# target to preprocess a source file
Function_SOFTMAX.cpp.i:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/Function_SOFTMAX.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Function_SOFTMAX.cpp.i
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/Function_SOFTMAX.cpp.i
.PHONY : Function_SOFTMAX.cpp.i

Function_SOFTMAX.s: Function_SOFTMAX.cpp.s

.PHONY : Function_SOFTMAX.s

# target to generate assembly for a file
Function_SOFTMAX.cpp.s:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/Function_SOFTMAX.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Function_SOFTMAX.cpp.s
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/Function_SOFTMAX.cpp.s
.PHONY : Function_SOFTMAX.cpp.s

Solver_EG.o: Solver_EG.cpp.o

.PHONY : Solver_EG.o

# target to build an object file
Solver_EG.cpp.o:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/Solver_EG.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Solver_EG.cpp.o
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/Solver_EG.cpp.o
.PHONY : Solver_EG.cpp.o

Solver_EG.i: Solver_EG.cpp.i

.PHONY : Solver_EG.i

# target to preprocess a source file
Solver_EG.cpp.i:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/Solver_EG.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Solver_EG.cpp.i
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/Solver_EG.cpp.i
.PHONY : Solver_EG.cpp.i

Solver_EG.s: Solver_EG.cpp.s

.PHONY : Solver_EG.s

# target to generate assembly for a file
Solver_EG.cpp.s:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/Solver_EG.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Solver_EG.cpp.s
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/Solver_EG.cpp.s
.PHONY : Solver_EG.cpp.s

Solver_ME_DUAL.o: Solver_ME_DUAL.cpp.o

.PHONY : Solver_ME_DUAL.o

# target to build an object file
Solver_ME_DUAL.cpp.o:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/Solver_ME_DUAL.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Solver_ME_DUAL.cpp.o
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/Solver_ME_DUAL.cpp.o
.PHONY : Solver_ME_DUAL.cpp.o

Solver_ME_DUAL.i: Solver_ME_DUAL.cpp.i

.PHONY : Solver_ME_DUAL.i

# target to preprocess a source file
Solver_ME_DUAL.cpp.i:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/Solver_ME_DUAL.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Solver_ME_DUAL.cpp.i
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/Solver_ME_DUAL.cpp.i
.PHONY : Solver_ME_DUAL.cpp.i

Solver_ME_DUAL.s: Solver_ME_DUAL.cpp.s

.PHONY : Solver_ME_DUAL.s

# target to generate assembly for a file
Solver_ME_DUAL.cpp.s:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/Solver_ME_DUAL.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Solver_ME_DUAL.cpp.s
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/Solver_ME_DUAL.cpp.s
.PHONY : Solver_ME_DUAL.cpp.s

Solver_NEW.o: Solver_NEW.cpp.o

.PHONY : Solver_NEW.o

# target to build an object file
Solver_NEW.cpp.o:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/Solver_NEW.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Solver_NEW.cpp.o
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/Solver_NEW.cpp.o
.PHONY : Solver_NEW.cpp.o

Solver_NEW.i: Solver_NEW.cpp.i

.PHONY : Solver_NEW.i

# target to preprocess a source file
Solver_NEW.cpp.i:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/Solver_NEW.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Solver_NEW.cpp.i
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/Solver_NEW.cpp.i
.PHONY : Solver_NEW.cpp.i

Solver_NEW.s: Solver_NEW.cpp.s

.PHONY : Solver_NEW.s

# target to generate assembly for a file
Solver_NEW.cpp.s:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/Solver_NEW.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Solver_NEW.cpp.s
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/Solver_NEW.cpp.s
.PHONY : Solver_NEW.cpp.s

Solver_SGD.o: Solver_SGD.cpp.o

.PHONY : Solver_SGD.o

# target to build an object file
Solver_SGD.cpp.o:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/Solver_SGD.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Solver_SGD.cpp.o
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/Solver_SGD.cpp.o
.PHONY : Solver_SGD.cpp.o

Solver_SGD.i: Solver_SGD.cpp.i

.PHONY : Solver_SGD.i

# target to preprocess a source file
Solver_SGD.cpp.i:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/Solver_SGD.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Solver_SGD.cpp.i
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/Solver_SGD.cpp.i
.PHONY : Solver_SGD.cpp.i

Solver_SGD.s: Solver_SGD.cpp.s

.PHONY : Solver_SGD.s

# target to generate assembly for a file
Solver_SGD.cpp.s:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/Solver_SGD.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Solver_SGD.cpp.s
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/Solver_SGD.cpp.s
.PHONY : Solver_SGD.cpp.s

blas/daxpy.o: blas/daxpy.c.o

.PHONY : blas/daxpy.o

# target to build an object file
blas/daxpy.c.o:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/blas/daxpy.c.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/blas/daxpy.c.o
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/blas/daxpy.c.o
.PHONY : blas/daxpy.c.o

blas/daxpy.i: blas/daxpy.c.i

.PHONY : blas/daxpy.i

# target to preprocess a source file
blas/daxpy.c.i:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/blas/daxpy.c.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/blas/daxpy.c.i
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/blas/daxpy.c.i
.PHONY : blas/daxpy.c.i

blas/daxpy.s: blas/daxpy.c.s

.PHONY : blas/daxpy.s

# target to generate assembly for a file
blas/daxpy.c.s:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/blas/daxpy.c.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/blas/daxpy.c.s
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/blas/daxpy.c.s
.PHONY : blas/daxpy.c.s

blas/ddot.o: blas/ddot.c.o

.PHONY : blas/ddot.o

# target to build an object file
blas/ddot.c.o:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/blas/ddot.c.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/blas/ddot.c.o
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/blas/ddot.c.o
.PHONY : blas/ddot.c.o

blas/ddot.i: blas/ddot.c.i

.PHONY : blas/ddot.i

# target to preprocess a source file
blas/ddot.c.i:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/blas/ddot.c.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/blas/ddot.c.i
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/blas/ddot.c.i
.PHONY : blas/ddot.c.i

blas/ddot.s: blas/ddot.c.s

.PHONY : blas/ddot.s

# target to generate assembly for a file
blas/ddot.c.s:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/blas/ddot.c.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/blas/ddot.c.s
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/blas/ddot.c.s
.PHONY : blas/ddot.c.s

blas/dnrm2.o: blas/dnrm2.c.o

.PHONY : blas/dnrm2.o

# target to build an object file
blas/dnrm2.c.o:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/blas/dnrm2.c.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/blas/dnrm2.c.o
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/blas/dnrm2.c.o
.PHONY : blas/dnrm2.c.o

blas/dnrm2.i: blas/dnrm2.c.i

.PHONY : blas/dnrm2.i

# target to preprocess a source file
blas/dnrm2.c.i:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/blas/dnrm2.c.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/blas/dnrm2.c.i
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/blas/dnrm2.c.i
.PHONY : blas/dnrm2.c.i

blas/dnrm2.s: blas/dnrm2.c.s

.PHONY : blas/dnrm2.s

# target to generate assembly for a file
blas/dnrm2.c.s:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/blas/dnrm2.c.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/blas/dnrm2.c.s
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/blas/dnrm2.c.s
.PHONY : blas/dnrm2.c.s

blas/dscal.o: blas/dscal.c.o

.PHONY : blas/dscal.o

# target to build an object file
blas/dscal.c.o:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/blas/dscal.c.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/blas/dscal.c.o
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/blas/dscal.c.o
.PHONY : blas/dscal.c.o

blas/dscal.i: blas/dscal.c.i

.PHONY : blas/dscal.i

# target to preprocess a source file
blas/dscal.c.i:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/blas/dscal.c.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/blas/dscal.c.i
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/blas/dscal.c.i
.PHONY : blas/dscal.c.i

blas/dscal.s: blas/dscal.c.s

.PHONY : blas/dscal.s

# target to generate assembly for a file
blas/dscal.c.s:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/blas/dscal.c.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/blas/dscal.c.s
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/blas/dscal.c.s
.PHONY : blas/dscal.c.s

linear.o: linear.cpp.o

.PHONY : linear.o

# target to build an object file
linear.cpp.o:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/linear.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/linear.cpp.o
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/linear.cpp.o
.PHONY : linear.cpp.o

linear.i: linear.cpp.i

.PHONY : linear.i

# target to preprocess a source file
linear.cpp.i:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/linear.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/linear.cpp.i
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/linear.cpp.i
.PHONY : linear.cpp.i

linear.s: linear.cpp.s

.PHONY : linear.s

# target to generate assembly for a file
linear.cpp.s:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/linear.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/linear.cpp.s
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/linear.cpp.s
.PHONY : linear.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

predict.o: predict.c.o

.PHONY : predict.o

# target to build an object file
predict.c.o:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/predict.c.o
.PHONY : predict.c.o

predict.i: predict.c.i

.PHONY : predict.i

# target to preprocess a source file
predict.c.i:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/predict.c.i
.PHONY : predict.c.i

predict.s: predict.c.s

.PHONY : predict.s

# target to generate assembly for a file
predict.c.s:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/predict.c.s
.PHONY : predict.c.s

train.o: train.c.o

.PHONY : train.o

# target to build an object file
train.c.o:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/train.c.o
.PHONY : train.c.o

train.i: train.c.i

.PHONY : train.i

# target to preprocess a source file
train.c.i:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/train.c.i
.PHONY : train.c.i

train.s: train.c.s

.PHONY : train.s

# target to generate assembly for a file
train.c.s:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/train.c.s
.PHONY : train.c.s

tron.o: tron.cpp.o

.PHONY : tron.o

# target to build an object file
tron.cpp.o:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/tron.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/tron.cpp.o
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/tron.cpp.o
.PHONY : tron.cpp.o

tron.i: tron.cpp.i

.PHONY : tron.i

# target to preprocess a source file
tron.cpp.i:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/tron.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/tron.cpp.i
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/tron.cpp.i
.PHONY : tron.cpp.i

tron.s: tron.cpp.s

.PHONY : tron.s

# target to generate assembly for a file
tron.cpp.s:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/tron.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/tron.cpp.s
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/tron.cpp.s
.PHONY : tron.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... train"
	@echo "... main"
	@echo "... predict"
	@echo "... Function_SOFTMAX.o"
	@echo "... Function_SOFTMAX.i"
	@echo "... Function_SOFTMAX.s"
	@echo "... Solver_EG.o"
	@echo "... Solver_EG.i"
	@echo "... Solver_EG.s"
	@echo "... Solver_ME_DUAL.o"
	@echo "... Solver_ME_DUAL.i"
	@echo "... Solver_ME_DUAL.s"
	@echo "... Solver_NEW.o"
	@echo "... Solver_NEW.i"
	@echo "... Solver_NEW.s"
	@echo "... Solver_SGD.o"
	@echo "... Solver_SGD.i"
	@echo "... Solver_SGD.s"
	@echo "... blas/daxpy.o"
	@echo "... blas/daxpy.i"
	@echo "... blas/daxpy.s"
	@echo "... blas/ddot.o"
	@echo "... blas/ddot.i"
	@echo "... blas/ddot.s"
	@echo "... blas/dnrm2.o"
	@echo "... blas/dnrm2.i"
	@echo "... blas/dnrm2.s"
	@echo "... blas/dscal.o"
	@echo "... blas/dscal.i"
	@echo "... blas/dscal.s"
	@echo "... linear.o"
	@echo "... linear.i"
	@echo "... linear.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... predict.o"
	@echo "... predict.i"
	@echo "... predict.s"
	@echo "... train.o"
	@echo "... train.i"
	@echo "... train.s"
	@echo "... tron.o"
	@echo "... tron.i"
	@echo "... tron.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

